### ISSUE TITLE
DSE bypass not working on 20H2 after KB5003173 update

### ISSUE THREAD

**Issue by mihaly044** [hfiref0x/KDU#6] opened 2021-05-13 17:11 UTC
The latest Windows update for 20H2 that is KB5003173, breaks the functionality of the DSE bypass.

Steps to reproduce:
- Upgrade your OS to the newest version available
- Run KDU as follows: `kdu.exe -dse 0`
- Observe the unchanged code integrity options value

KDU will report success in despite of the code integrity options value hasn't been altered. Hence, `NtLoadDriver` will report `STATUS_INVALID_IMAGE_HASH`.
I have also checked it using `NtQuerySystemInformation(SystemCodeIntegrityInformation...`  and here's the output of that:
```CODEINTEGRITY_OPTION_ENABLED=TRUE
CODEINTEGRITY_OPTION_TESTSIGN=FALSE
CODEINTEGRITY_OPTION_UMCI_ENABLED=FALSE
CODEINTEGRITY_OPTION_UMCI_AUDITMODE_ENABLED=FALSE
CODEINTEGRITY_OPTION_UMCI_EXCLUSIONPATHS_ENABLED=FALSE
CODEINTEGRITY_OPTION_TEST_BUILD=FALSE
CODEINTEGRITY_OPTION_PREPRODUCTION_BUILD=FALSE
CODEINTEGRITY_OPTION_DEBUGMODE_ENABLED=FALSE
CODEINTEGRITY_OPTION_FLIGHT_BUILD=FALSE
CODEINTEGRITY_OPTION_FLIGHTING_ENABLED=FALSE
CODEINTEGRITY_OPTION_HVCI_KMCI_ENABLED=FALSE
CODEINTEGRITY_OPTION_HVCI_KMCI_AUDITMODE_ENABLED=FALSE
CODEINTEGRITY_OPTION_HVCI_KMCI_STRICTMODE_ENABLED=FALSE
CODEINTEGRITY_OPTION_HVCI_IUM_ENABLED=TRUE

CodeIntegrityOptions=0x2001
```

I suspect the memory location of the target variable has changed.

**Comment by hfiref0x** [comment] 2021-05-13 18:34
Yes, CI.DLL now uses Microsoft WIL extensively. It numerous calls at **CiInitialize** ruins previous algorithm of **CipInitialize** lookup.

![ci](https://user-images.githubusercontent.com/10708977/118170517-60d8b700-b454-11eb-8f2d-4a377fc6c9bc.jpg)

**Comment by mihaly044** [comment] 2021-05-13 23:57
Thanks, @hfiref0x !
I think I have got it working thanks to your accurate information.
I'll make a PR later today after I'm done testing.

**Comment by hfiref0x** [comment] 2021-05-14 02:16
Thanks, but no need. I'm planning this part completely.

**Comment by hfiref0x** [comment] 2021-05-14 08:38
The code for DSE manipulations are from DSEFix in mostly unmodified state. It turns out it also has some very ancient bug which one I likely added when I was moving this repository to the github from kernelmode.info. This also will fixed.

**Comment by Narumiii** [comment] 2021-05-14 19:03
I can confirm after the commit it still dones't work

**Comment by Narumiii** [comment] 2021-05-14 19:04
![image](https://user-images.githubusercontent.com/37037181/118317197-085af580-b4f8-11eb-93ce-2c80601d6b09.png)

**Comment by hfiref0x** [comment] 2021-05-15 01:41
There has been no commits in master branch. Try exe from dev111 instead (https://github.com/hfiref0x/KDU/blob/v111/Bin/kdu.exe). If it still fails to work then unload your **Windows\system32\CI.DLL** somewhere (not on github) and post here a link to it.

**Comment by Narumiii** [comment] 2021-05-15 15:16
Sorry my fault you are right these version works, anyways if needed here is my CI.dll https://anonfiles.com/R5R9r2w3u6/ci_dll

**Comment by hfiref0x** [comment] 2021-05-15 16:02
Thanks, I've checked your file. KDU from dev111 should work fine with it.

**Closed** 2021-05-16 02:43 UTC
Labels: bug, enhancement
